services:
  mineru-service-official:
    build:
      context: .
      dockerfile: Dockerfile.official
    container_name: mineru-service-official
    restart: always
    volumes:
      - ./models:/models
      - ./app.py:/app/app.py
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  nginx:
    image: nginx:latest
    container_name: nginx-official
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mineru-service-official 