version: '3.8'

services:
  mineru:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mineru-service
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./models:/models
      - ./output:/output
      - ./uploads:/uploads
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - MINERU_TOOLS_CONFIG_JSON=/app/magic-pdf.json
    volumes:
      - ./data:/data
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONUNBUFFERED=1  # 确保Python输出不被缓存
      - UVICORN_TIMEOUT=300  # 5分钟超时
    working_dir: /app
    command: bash -c 'source /opt/mineru_venv/bin/activate && python -m uvicorn app:app --host 0.0.0.0 --port 8000 --workers 1 --log-level debug'
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mineru
