version: '3.8'

services:
  mineru:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mineru-service
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./models:/models:ro
      - ./output:/output
      - ./uploads:/uploads
      - ./data:/data
      - ./config:/root
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - MINERU_TOOLS_CONFIG_JSON=/app/magic-pdf.json
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONUNBUFFERED=1
      - UVICORN_TIMEOUT=300
    working_dir: /app
    command: bash -c "chmod +x /app/start_app.sh && /app/start_app.sh"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mineru
