version: '3'
services:
  mineru:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./data:/data
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    working_dir: /app
    command: >
      bash -c '
        source /opt/mineru_venv/bin/activate &&
        python -m uvicorn app:app 
        --host 0.0.0.0 
        --port 8000 
        --workers 1
        --timeout-keep-alive 75
        --limit-concurrency 4
        --backlog 2000
        '
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
