version: '3'
services:
  mineru:
    build: .
    ports:
      - "8000:8000"  # 暂时对外暴露端口以便调试
    volumes:
      - ./app:/app
      - ./data:/data
      - ./models:/app/models  # 挂载模型目录
      - ./scripts:/app/scripts
      - ./tests:/app/tests
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONUNBUFFERED=1  # 确保Python输出不被缓存
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        limits:
          memory: 16G  # 限制内存使用
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    working_dir: /app
    command: python -m uvicorn app:app --host 0.0.0.0 --port 8000 --workers 1
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mineru
